float64 lat			# target position (deg * 1e7)
float64 lon			# target position (deg * 1e7) 
float32 alt			# target position
float32 vy			# target vel in y
float32 vx			# target vel in x
float32 vz			# target vel in z 
uint8 est_cap # target reporting capabilities

float32 roll_body				# body angle in NED frame
float32 pitch_body				# body angle in NED frame
float32 yaw_body				# body angle in NED frame
